### ISSUE TITLE
Do you want me to add tests ?

### ISSUE THREAD

**Issue by hyphaene** [jaketrent/redux-types#2]
Hi,

Since I use the package on a React project which is unit-tested, I had to write some tests.

So, I offer to add some tests inside the core function
- check if all args are strings
- check if all args ( except with the first ) are unique 
And add a test file to unit test the function .

It would allow to use the package with some helpers in case of misuse, avoid each developer to test the function again, and the tested file would garanty the expected behavior.

What do you think of it ?

Cheers.

**Comment by jaketrent** [comment]
Hi @hyphaene .  Yes, interesting tests that you think of would be great to add.  

As you describe these tests though, they sound like runtime assertions that you're making on input to the function, not necessarily unit tests.  For instance, how do you know if all the types are unique until you call the function?  And does that mean you want to throw an error if they're not unique or something like that?

**Comment by hyphaene** [comment]
The idea would be to integrate runtime assertions to check unicity, and ensure all args are strings.

And (  I admit that this second point is really optional ), create a little unit test file, which would test, on several inputs ( let's say one => ok, two => not unique keys , three => wrong type ), to ensure that the function behave as expected, either by throwing the right error, or output the built types object ( like a guarantee )

**Comment by jaketrent** [comment]
@hyphaene ok, great.  Yeah, this matches what I imagined you meant.  Sounds good to me.  I think these additional helps would be nice.

**Comment by hyphaene** [comment]
Perfect.
I'll make a PR tonight !
