### ISSUE TITLE
pass array(s) to the function for other parameters than the first

### ISSUE THREAD

**Issue by hyphaene** [jaketrent/redux-types#3]
Do you want me to add the possibilty to pass one or multiple arrays of strings as parameters ( except for the first ).

It could be usefull, since we could compose all the types with generic + specific arrays .

Example :

```
const genericArray1 = ['CREATE', 'UPDATE', 'DELETE'] // used a lot

const specificModalArray = ['ADD_USER', 'TOGGLE' ]
const specificContextArray = ['FETCH_CONTEXT', 'FETCH_CHILDREN' ]

const ModalTypes = types('Modal', genericArray1, specificModalArray)
const ContextTypes =  types('Context', genericArray1, specificContextArray)

console.log(ModalTypes)
 // prints:

// { 
//    CREATE : Modal/CREATE,
//    UPDATE : Modal/UPDATE,
//    DELETE : Modal/DELETE,
//    ADD_USER : Modal/ADD_USER,
//    TOGGLE : Modal/TOGGLE,
// }

console.log(ContextTypes)
 // prints:

// { 
//    CREATE : Context/CREATE,
//    UPDATE : Context/UPDATE,
//    DELETE : Context/DELETE,
//    FETCH_CONTEXT : Context/FETCH_CONTEXT,
//    FETCH_CHILDREN : Context/FETCH_CHILDREN,
// }

```
Of course, we could spread the arrays for computing the arrays as a list of strings, but the function could also handle it for us ;)

I could do it today.

It you want be to do so, and also add the tests, i'll handle this case also of course.

Cheers.

**Comment by jaketrent** [comment]
Hey @hyphaene ,   Whether we want to do this is a bit unclear to me.  You are the 2nd person to suggest that we make the 2nd arg an array instead of rest arguments.  I'm fine with that.  I don't see a strong use case for sending in multiple arrays though.  I think a single array should do the job.

**Comment by hyphaene** [comment]
I wanted to let the function manage whatever combinations of strings / arrays we would pass into it.

But after some tests, I **retract** myself on this point.

Thats why : 
If we allow one array, or many, or an combinations of arrays and strings as parameter, or whatever, it **would loudly increase the computing cost** of the function which would have to **check for types**, **spread, check for other arg types, spread or push** .. and so on, to build the final array to map on.

And this writing : 

`const myTypes = types('Constant', ...[...['ijij', 'opopop', ...['kokok']]])
`

is **perfectly functionnal**, and renders as expected. 
( assuming the strings are the visual render of array composing ( at multiple level ) eventually needed by the developer.

**So I suggest we keep the actual behavior** and let the developer make the composition by himself, since allowing array would increase the number of cases to deal with ( one string after are array would be okay or not ? ), and so the number of computing inside the core function, and then the tests to run .

Sticking with a list of strings would **keep the validity test to its minimum** ( and with it the **computing cost**)
is it a strings, and is the array of args unique.

Do you agree ?

**Comment by jaketrent** [comment]
My favorite options are probably:

1. single array of strings
2. keep as-is, var args of strings

I'm fine with either.

**Comment by hyphaene** [comment]
Since changing the expected input would cause **breaking change** for the next release, here is what I suggest :

I make a **first PR** :
- with keeping the list of strings as expected args
- with tests
- I implement the new function, then I call it inside the actual one ( currying ) with a warning, to let know the developer that the next major release will expect an array of strings as second arg.
=> You can publish this as the next **minor** version release

I make a **second PR :** 
- I only use the new function 
- I update the tests
- I update the README
- I remove the warning
=> you can publish this as the next **major** version release

This way, developers which use this package in the **current major release won't see their code broken**, will be noticed that the **next version will expect an array** as second parameter, and it will be **painless** for whoever gets the package directly with the **latest major release**.

Do you agree ?
