### ISSUE TITLE
engine :node 8

### ISSUE THREAD

**Issue by hyphaene** [jaketrent/redux-types#7]
Hi,

I would like to know why the engine points to the 8.x version of node in the package.json ?

Is there any change which forces the upgrade to the 8.x version ?

Max.

**Comment by jaketrent** [comment]
No, there's no change that forces this.  Just keeping updated to the latest version and matching the project nvmrc. Is there some bad effect that's been created by this change?

**Comment by hyphaene** [comment]
The fact is that if some projects are using some packages which are dependents of a specific version of node,  let's say package xxx runs on node 4 or 7, but has not been udpated to work with node 8, they won't be able to upgrade the package without breaking the rest of their code
Since this package is not dependend of any version of node, I'd suggest to remove the "engine"  to keep it globally available , regardless of the node version of the project it will be installed

**Comment by jaketrent** [comment]
sounds fine to me.  i'll remove it.

**Comment by jaketrent** [comment]
published in 2.0.3
